/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testDB;

import java.sql.*;
import java.sql.DriverManager;

public class App {

    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost/testDB", "root", "1234")) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet rs = stmt.executeQuery("SELECT * from CUSTOMERS")) {
                    //position result to first
                    rs.first();
                    System.out.print(rs.getString(1)+ "\t");
                    System.out.print(rs.getString(2)+ "\t");                    
                    System.out.print(rs.getString(3)+ "\t");
                    System.out.print(rs.getString(4)+ "\t");
                    System.out.print(rs.getString(5)+ "\t");
                    // System.out.println(rs.getString("nama"));
                }
            }
        }
    }
}